name: Build ProMapper APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair projeto ZIP
        run: |
          unzip -o ProMapper-GitHub-APK.zip -d promapper

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Compilar APK
        working-directory: promapper
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: ProMapper-debug-apk
          path: promapper/app/build/outputs/apk/debug/app-debug.apk
